### ISSUE TITLE
Very high CPU usage in various scenarios

### ISSUE THREAD

**Issue by Gert-dev** [SeeLook/metronomek#2]
Hello

I just discovered this neat metronome through Flathub and took it for a spin. Overall it works well, but I noticed that various things cause it to start using a high amount of CPU usage:

* Opening the left sidebar by clicking the traffic lights. As long as it is open, CPU usage stays high. Closing it fixes it.
* Unfocusing the application by alt-tabbing to another. Focusing it again lowers the CPU usage again.
* Sometimes nothing out of the ordinary.

I don't know what it's doing in the background when any of this happens. This is on Arch Linux x64 with GNOME and an NVIDIA GPU (proprietary drivers, in case it's something GPU-related).

I discovered all three of these because my fans are very passive and become very loud when anything significantly starts stressing the CPU, which turned to be this application in the above three cases, verified by checking `top`.

**Comment by SeeLook** [comment]
Hello @Gert-dev ,

Thank You a lot for calling this issue.
Because I've never caught Metronomek on taking CPU much, in opposite CPU bores when Metronomek is working.
But I didn't test so many scenarios, so I don't deny I may do something about it.

I'm on Arch Linux the same as You but with KDE Plasma. Even if I tried other DE - it was under VirtualBox -so probably. doesn't count. 
I just tested it once more - either native build and AppImage - works fine.
I will try flatpak meanwhile - I did before but under VM.

Would You be so kind and try [AppImage](https://sourceforge.net/projects/metronomek/files/Metronomek-0.5.0/Metronomek-0.5.0-b167-x86_64.AppImage) and/or [AUR package](https://aur.archlinux.org/packages/?O=0&K=metronomek).
It will narrow down possible sources of the problem.

May your fans stay calm :-)

**Comment by Gert-dev** [comment]
Sure! I tried the AUR build just now. Weirdly enough I cannot reproduce the CPU usage using the sidebar or unfocusing, but if I click the green button to start the metronome once, and then click it again to stop, CPU usage rises to 100% and never goes down. This in turn did not happen in the Flatpak.

(Also, I now effectively cannot test the Flatpak anymore because I'm suddenly hitting https://github.com/flatpak/flatpak/issues/4245, but hopefully I can resolve that soon.)

**Comment by SeeLook** [comment]
Got it!
Totally my fault, I've limped on that already a few years ago but I forgot.
PulseAudio stream has to be aborted and then closed otherwise there is what we had.

But that path is for development branch.
I have to cherry-pick it to some stable one and then release something like 0.5.1.
On it. But the new flatpak rather tomorrow.
